### ISSUE TITLE
Add a character counter to the prompt box

### ISSUE THREAD

**Issue by mortscode** [abm-werbeagentur/craft-chatgpt#1]
When I type a prompt and it exceeds 300 characters, I get redirected to a Craft error page (in dev mode). 

It would be nice to know how many characters I currently have and the total limit.

Also, you should update your documentation with some prompt instructions. It's not clear that the `[[text]]` variable is needed to evaluate the content in the text field. I eventually figured it out by looking at your screenshots on the plugin page.

Thanks!!

**Comment by HigumaSan4050** [comment]
Hi,

which version of the plugin and of Craft CMS is installed

**Comment by HigumaSan4050** [comment]
2.0.4 is out with the fix for this. Thanks!!
